# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Projconf < Formula
  desc "ProjConf CLI."
  homepage "https://github.com/train360-corp/projconf"
  version "1.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/train360-corp/projconf/releases/download/v1.1.1/projconf_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy,
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "ab9009833c8337a659498c1c069983c53467bd3111a0d46ff888e5829721eb1a"

      def install
        bin.install "projconf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/train360-corp/projconf/releases/download/v1.1.1/projconf_Darwin_arm64.tar.gz", using: CurlDownloadStrategy,
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "afa8c729ae452c62d7d318c25794015be9dc7a34443d4cc983a2916cf576e9b6"

      def install
        bin.install "projconf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/train360-corp/projconf/releases/download/v1.1.1/projconf_Linux_x86_64.tar.gz", using: CurlDownloadStrategy,
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "58637f0520f2f70e44b0a37cf621ab8b361b9b64b3ecb69ce944ff683ecb1f40"
      def install
        bin.install "projconf"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/train360-corp/projconf/releases/download/v1.1.1/projconf_Linux_arm64.tar.gz", using: CurlDownloadStrategy,
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "3c86da1c38f2b2b4b609261e45ade20f09f578731ae51b74007e9d96ae878889"
      def install
        bin.install "projconf"
      end
    end
  end

  def caveats
    <<~EOS
      projconf --help
    EOS
  end

  test do
    system "#{bin}/projconf --version"
  end
end
