# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Projconf < Formula
  desc "ProjConf CLI."
  homepage "https://github.com/train360-corp/projconf"
  version "1.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/train360-corp/projconf/releases/download/v1.2.2/projconf_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy,
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "1ba839ee20aef810e0ba1a9768a43ec49626c5f6d33717d551668e80e8ba4b45"

      def install
        bin.install "projconf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/train360-corp/projconf/releases/download/v1.2.2/projconf_Darwin_arm64.tar.gz", using: CurlDownloadStrategy,
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "6e399debbd85da4c86e56db5526339b1361df3c3ea120a51e2f20c7c12dbde69"

      def install
        bin.install "projconf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/train360-corp/projconf/releases/download/v1.2.2/projconf_Linux_x86_64.tar.gz", using: CurlDownloadStrategy,
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "29dcf7ebf740731bb87a0353549ef402ebaeaaa71168f5e14b693112553ddf81"
      def install
        bin.install "projconf"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/train360-corp/projconf/releases/download/v1.2.2/projconf_Linux_arm64.tar.gz", using: CurlDownloadStrategy,
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "c0075f1fcda951f0d2d345b4a4aa6b04d7edca145b036b2d6ebf1201376cb72d"
      def install
        bin.install "projconf"
      end
    end
  end

  def caveats
    <<~EOS
      projconf --help
    EOS
  end

  test do
    system "#{bin}/projconf --version"
  end
end
