# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Projconf < Formula
  desc "ProjConf CLI."
  homepage "https://github.com/train360-corp/projconf"
  version "0.0.17"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/train360-corp/projconf/releases/download/v0.0.17/projconf_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy,
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "964938d90470abf69ce60f0c7b5ea22fe6f65581fec26b72ea140ed30b743842"

      def install
        bin.install "projconf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/train360-corp/projconf/releases/download/v0.0.17/projconf_Darwin_arm64.tar.gz", using: CurlDownloadStrategy,
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "636c87707dfd1ce76fb26bd927717e2338e1ccb1f458735d1897cd7b8127cac7"

      def install
        bin.install "projconf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/train360-corp/projconf/releases/download/v0.0.17/projconf_Linux_x86_64.tar.gz", using: CurlDownloadStrategy,
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "8de61ec8aec7ea36a5e51da0f3d97376e870c9aa01ea15256ec415c0aa993c26"
      def install
        bin.install "projconf"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/train360-corp/projconf/releases/download/v0.0.17/projconf_Linux_arm64.tar.gz", using: CurlDownloadStrategy,
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "62b9071365e5059d00e2dac13849df1bd185d40d7b5ff46583dd708eed36aa96"
      def install
        bin.install "projconf"
      end
    end
  end

  def caveats
    <<~EOS
      projconf --help
    EOS
  end

  test do
    system "#{bin}/projconf --version"
  end
end
